version: '2.4'

services:
    samsung-ac:
        image: 'samburney/py-samsung-ac:latest'
        restart: 'unless-stopped'
        build:
            context: '.'
            dockerfile: 'Dockerfile'
        volumes:
            - './samsung_ac/config.ini:/app/samsung_ac/config.ini'
