version: '2.4'

services:
    python:
        image: 'python-samsung-ac:dev'
        build:
            context: '.'
            dockerfile: 'Dockerfile.dev'
        command: /bin/sh -c "while sleep 1000; do :; done"
        volumes:
            - '.:/app'